version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12Sanjay@raj
      MYSQL_DATABASE: trading_db
    ports:
      - "3000:3000"          # ✅ MySQL running on port 3000
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    command: --port=3000     # ✅ Force MySQL to use port 3000
    restart: always

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3000          # ✅ Use MySQL on port 3000
      DB_USER: root
      DB_PASSWORD: 12Sanjay@raj
      DB_NAME: trading_db
    restart: always

networks:
  app-network:

volumes:
  mysql-data:
